### ISSUE TITLE
Class\ProcessWire\FieldtypeWebmentions does not exist

### ISSUE THREAD

**Issue by rzelnik** [gRegorLove/ProcessWire-Webmention#23]
I just installed all the Webmention modules (version 2.0.0) on ProcessWire 3.0.164. It looks like everything is installed well. I created the field for webmentions and added it to the template.

It returns this error message in Modules.php on line 3420:

Exception has occurred.
ReflectionException: Class\ProcessWire\FieldtypeWebmentions does not exist

Some debugging revealed that in wire/core/Modules.php > function getModuleFile > $dirname expects the FieldtypeWebmentions to be located here:

`wire/modules/Fieldtype/FieldtypeWebmentions.module.php`

while in reality it is located here:

`site/modules/Webmention/FieldtypeWebmentions/FieldtypeWebmentions.module.php`

**Comment by gRegorLove** [comment]
Hi @rzelnik. This sounds like you might not have all of the modules installed that comprise this plugin, and ProcessWire's core module loader is falling back to looking for the `FieldtypeWebmentions` module in the core directory, `/wire`. There isn't any code in these modules that looks for files in the `/wire` directory.

Can you confirm you have installed:
* Webmention
* FieldtypeWebmentions
* InputfieldWebmentions
* ProcessWebmentionsManager

The first module, `Webmention`, should automatically install the others, so it may be easiest to uninstall whichever of the modules you have above, then install `Webmention`. You can also try installing them individually.

If you're still running into issues, please let me know the steps so I can reproduce.

**Comment by rzelnik** [comment]
I uninstalled and deleted all *webmention* modules and installed them again (by installing the parent Webmention module), ten I reproduced the installation process, and now it looks fine. I think that the previous error is somehow connected with the fact that I previously renamed the webmention field. When I rename the webmention field now, it immediately returns these error messages:

( ! )  Fatal error: Uncaught Error: Maximum function nesting level of '256'  reached, aborting! in  /processwire/wire/core/Wire.php on line 1715
( ! ) Error: Maximum function nesting level of '256' reached, aborting! in /processwire/wire/core/Wire.php on line 1715

**Comment by gRegorLove** [comment]
From your code on the forum, this line needs to use whatever you renamed the field:

`<?= $page->Webmentions->render(); ?>`

For example, if you changed it to `example_field` the line would need to be:

`<?= $page->example_field->render(); ?>`

**Comment by rzelnik** [comment]
I am sorry for late response. I will try to implement it again from scratch and then I will let know how it works.

**Comment by gRegorLove** [comment]
No problem! If you have all the modules installed, I don't think you need to start from scratch. You mainly need to use the correct field name in the code snippet if you renamed it from "Webmentions".

**Comment by rzelnik** [comment]
It seems to be working now. I think that there was just some mismatch in the field name (Webmentions <> webmentions).

**Comment by gRegorLove** [comment]
Glad it's working!
